### ISSUE TITLE
Installation script problem task list

### ISSUE THREAD

**Issue by KritantaDev** [DragonBuild/dragon#66]
- [ ] Users may have a misconfigured path variable
- [ ] Users' python installations may ignore the pyyaml dependency
- [ ] Users should be able to configure install dir with a cli arg, or be capable of migrating itself later, setup should be quiet by default
